name: Publish to Github Wiki
author: nimblehq

description: Our Github Action publishes and updates your documentation to your project's Github Wiki!

branding: 
  icon: book
  color: orange

inputs:
  USER_TOKEN: 
    description: 'The Github Personal Access Token for this action to use.'
    required: true
  USER_NAME:
    description: 'The username of the user/bot of the provided USER_TOKEN'
    required: true
  USER_EMAIL:
    description: 'The email of the user/bot of the prodived USER_TOKEN'
    required: true

runs:
  using: docker
  image: Dockerfile
