name: Publish to Github Wiki
author: nimblehq

description: Our Github Action publishes and updates your documentation to your project's Github Wiki!

branding: 
  icon: book
  color: orange

inputs:
  user_access_token: 
    description: 'The Github Personal Access Token for this action to use'
    required: true
  user_name:
    description: 'The username of the user/bot of the provided user_access_token'
    required: true
  user_email:
    description: 'The email of the user/bot of the prodived user_access_token'
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.user_access_token }}
    - ${{ inputs.user_name }}
    - ${{ inputs.user_email }}
